/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package project_m;

import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 *
 * @author Elios
 */
public class dbPatientRegister {
    public static boolean insertPatient(String firstName, String lastName, String password, String address, String tel){
        try{
        dbConnection dbconnect = new dbConnection();
        Connection con = dbconnect.getConnection();
        
        String sql="INSERT INTO `clinic`.`patient` (`firstName`, `lastName`, `password`, `address`, `tel`) VALUES (?,?,?,?,?);";
        //Patient have a unique ID generated by the database
        
        PreparedStatement stmt=con.prepareStatement(sql);
        stmt.setString(1,firstName);
        stmt.setString(2,lastName);
        stmt.setString(3,MD5.getMd5(password)); //hashed password
        stmt.setString(4,address);
        stmt.setString(5,tel);
        
        int i=stmt.executeUpdate();
            if(i>0){
                return true;
            }
            else{
                return false;
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
            return false;
        }
    }
}
